language: cpp

jobs:
  include:
    - os: windows
      arch: amd64
      env: OS=windows
branches:
  only:
    - master

script:
    - mkdir builds
    - cd builds
    - cmake ..
    - cmake --build . --config release
    
after_success:
    - cd ..
    - open 139.159.160.103
    - $FTP_USER
    - $FTP_PASSWORD
    - put C:\Users\travis\build\weizengke\judge\build\VSBuild\bin\Release\judger.exe
    - bye