language: cpp
dist: bionic

jobs:
  include:
    - os: windows
      arch: amd64
      env: OS=windows
    - os: linux

branches:
  only:
    - master

script:
    - mkdir builds
    - cd builds
    - cmake ..
    - cmake --build . --config release
after_success:
    - ll
    - curl -u [$FTP_USER]:[$FTP_PASSWORD] -T ../build/suse/bin/judger ftp://$FTP_IP/
