language: cpp

jobs:
  include:
    - os: windows
      arch: amd64
      env: OS=windows
branches:
  only:
    - master

script:
    - mkdir builds
    - cd builds
    - cmake ..
    - cmake --build . --config release
    
after_success:
    - ./upload.bat $FTP_USER $FTP_PASSWORD