#ifndef _JUDGE_CMD_H_
#define _JUDGE_CMD_H_

enum JUDGE_CMO_TBLID_EM {
	JUDGE_TBL_SHOW = 0,
	JUDGE_TBL_CFG,	
	JUDGE_TBL_HDU,	
};

enum JUDGE_CMO_SHOW_ID_EM {
	JUDGE_CMO_SHOW_DISPLAY = CMD_ELEMID_DEF(MID_JUDGE, JUDGE_TBL_SHOW, 0),
	JUDGE_CMO_SHOW_JUDGE_BRIEF,	
};

enum JUDGE_CMO_CFG_ID_EM {
	JUDGE_CMO_CFG_UNDO = CMD_ELEMID_DEF(MID_JUDGE, JUDGE_TBL_CFG, 0),
	JUDGE_CMO_CFG_JUDGE,
	JUDGE_CMO_CFG_VJUDGE,
	JUDGE_CMO_CFG_ENABLE,	
	JUDGE_CMO_CFG_JUDGE_SOLUTION_ID,	
	JUDGE_CMO_CFG_JUDGE_MGR_VIEW,	
	JUDGE_CMO_CFG_VJUDGE_MGR_VIEW,	
	JUDGE_CMO_CFG_MODE,	
	JUDGE_CMO_CFG_MODE_ACM,	
	JUDGE_CMO_CFG_MODE_OI,	
	JUDGE_CMO_CFG_TESTCASE_PATH,	
	JUDGE_CMO_CFG_SECURITY,
	JUDGE_CMO_CFG_AUTODETECT,
	JUDGE_CMO_CFG_AUTODETECT_INTERVAL,
	JUDGE_CMO_CFG_HDU_JUDGE,
	JUDGE_CMO_CFG_REMOTE_JUDGE,
	JUDGE_CMO_CFG_HDU_USER_NAME,
	JUDGE_CMO_CFG_HDU_USER_PSW,
	JUDGE_CMO_CFG_HDU_REMOTE_IP,
	JUDGE_CMO_CFG_HDU_REMOTE_PORT,
};

extern ULONG Judge_CfgCallback(void *pRcvMsg);
extern ULONG Judge_RegCmd();

#endif
